### ISSUE TITLE
Not working in DW 2014-05-05a "Ponder Stibbons"

### ISSUE THREAD

**Issue by f-nobre** [algorys/redissue#17]
Hi,

Latest version of Redissue not working in DokuWiki version 2014-05-05a "Ponder Stibbons". 

The page where I try to use the plugin only displays the name of the selected DW template, and has no page footer. 

Latest version of Redproject works fine in this version of DW.

I can only use Redissue v1.1 in this DW version 2014-05-05a. (works normal, but has less features)

**Comment by algorys** [comment]
Hi @f-nobre,

Have you some errors in your logs when using redissue ?

Because I've not check this version of DW since a long time.

**Comment by f-nobre** [comment]
Dear Matthieu

Thanks for your fast response and sorry for mine slow. I was trying to figure out where to find the logs for my server.

Below is the line generated in /var/log/apache2/error.log .   Everytime I try to load the page with the latest version of redisue, a new line is added to the error log. As explained before, v1.1 works, but I really wish to use latest version of redissue due to the new features.

[Mon Aug 21 04:34:55.135120 2017] [:error] [pid 1483] [client 172.26.223.10:52865] PHP Fatal error:  Call to a member function show() on null in /var/lib/dokuwiki/lib/plugins/redissue/redmine/redmine.php on line 30, 

Let me know if I can help any further. Thanks for your time on this, and for your wonderful plugins.

Best regards

Fabio

**Comment by algorys** [comment]
Hi,

It seems that plugin can't get your issue number... please check your syntax because before:

 `<redissue id=#xx > ... </redissue>`

was allowed. Now you have to follow this syntax: https://github.com/algorys/redissue#single-issue-syntax

I'm currently in holidays but I'll try to see on my side. Try also to update `Redmine API` to see if that solved your problem.

**Comment by f-nobre** [comment]
Hi

I am using the new syntax. New syntax works also in v1.1

I am mostly interested in the possibility to show a list of all tasks in a project, with syntax 
`<redissue project="myproject" tracker="" />
`
My redmine is version 2.5.3.stable. I really don't want to mess with it because it is working perfect, including some plugins that might not work in higher versions, besides I think the API of my redmine version is enough for what redissue needs. But I may be wrong. 
http://www.redmine.org/projects/redmine/wiki/Rest_api 
I don't know if I can update the API without updating redmine.

Dont know if this is relevant, but I use LDAP authentication for my users(I use Univention server for LDAP, its a free linux AD)

Another solution would be if Redproject (which works for me) could list the issues (instead of just counting them)
Best regards

**Comment by f-nobre** [comment]
Hi Mattieu,

This is as far as I went trying to debug.

I cloned the VM where my wiki runs.

I updated the clone to DW to latest version. (Release 2017-02-19c "Frusterick Manners")

I updated redissue to the latest version.

Even this way, I still get the same behavior, redproject works, redissue does not,
![image](https://user-images.githubusercontent.com/31111805/29550311-802777e2-86e3-11e7-8b8f-353755aa681f.png)



I am using this code in the page
`<redissue id="#277" />`

`<redissue id="#244" />`

Which works fine in redissue v1.1

And I get this in the logs

**PHP Fatal error:  Call to a member function show() on null in /var/lib/dokuwiki/lib/plugins/redissue/redmine/redmine.php on line 30**

I also tried this syntax
`<redissue project="sistema-resultado-financeiro" tracker="" />`
without success

**Comment by f-nobre** [comment]
One more info: My redmine version 2.5.3.stable API is working fine with several different android redmine apps, including task edits via app. And since now I have upgraded DW, it seems to be a bug in redissue code, since redproject works. Thanks for your efforts, Best regards.

**Comment by algorys** [comment]
@f-nobre I was talking about Php Redmine API 😉 See https://github.com/algorys/redissue/blob/master/README.md#requirements for more details. (Go to your vendor folder, `git pull` and `git checkout` to last version).

I'll look in September for debugging when I go back to work.

**Comment by f-nobre** [comment]
Dear Matthieu. Problem solved!

I had installed Php Redmine API as per your instructions, inside `/usr/share/php` so it could be used by both RedIssue and RedProject. However only RedProject was working.

As I was browsing the server, I noticed a folder `/usr/share/dokuwiki/vendor`, so I tried installing the API inside this folder as well and voilá! RedIssue worked in current version.
My server is Debian based. It is this VM https://www.turnkeylinux.org/dokuwiki 

So I suggest you update the instructions to inform about this (that maybe the API also needs to be installed in this folder), To save you from other similar case.

Please close this case. Sorry for the false bug during your vacations. I cannot thank you enough for making this plugin. We use Dokuwiki and Redmine a lot. Redissue is a blessing for us. Thank you very much. If one day you come to Brazil (Jericoacoara), I will buy you a beer for sure!!

Best Regards

**Comment by f-nobre** [comment]
Hi Again,

One last peanut detail is the fact that the template name appears at the top of the page, when redissue is used in the page (if I select another template in DW configs, the name in the page changes):
![image](https://user-images.githubusercontent.com/31111805/29705009-920bb542-8952-11e7-8112-0f3b293ca9d8.png)

**Comment by algorys** [comment]
Update redissue will solve this last problem 😉 

Thanks for your support @f-nobre

**Comment by f-nobre** [comment]
Updated and working beatifully! Thanks!

**Comment by algorys** [comment]
@f-nobre you're welcome. You can ⭐️ github project if you want.
