### ISSUE TITLE
Choosing between bootstrap and normal styling should be configurable

### ISSUE THREAD

**Issue by Isammoc** [algorys/redissue#2]
Presently, two versions are distinct: with or without bootstrap.

Using bootstrap css should be done with enabling it in configuration, not during installation.

Now, it seems that the projet is forked from normal to bootstrap.

**Comment by algorys** [comment]
Yes that's a temporary solution, because I've to work on dokuwiki version before to ensure it display all information correctly.

But your idea to set it in configuration is not bad, I will keep this choice

**Comment by algorys** [comment]
That's done.
