### ISSUE TITLE
Redissue does not work if <redissue> tag is inside list

### ISSUE THREAD

**Issue by selivan** [algorys/redissue#5]
Dokuwiki version: 2015-08-10a "Detritus"
Dokuwiki template: dokuwiki (standard template)
Redissue version: current master (commit f13acd67283d8eadaaced8f3d5bc9cee4559a690 )

Works:

```
issue: <redissue id='#482' />
```

Does not work:

```
  * issue: <redissue id='#482' />
```

Result in page source:

``` html
<ul>
<li class="level1"><div class="li"> issue: &lt;redissue id=&#039;#482&#039; /&gt;</div>
</li>
</ul>
```

**Comment by algorys** [comment]
Ok.

I'm very busy next month but I'll try to find a solution.

**Comment by algorys** [comment]
Now, redissue can work inside lists.
