### ISSUE TITLE
Option to disable full view, leaving just title and labels [enhancement]

### ISSUE THREAD

**Issue by selivan** [algorys/redissue#8]
I use redissue to insert a short link like this: "#111 - horrible errors in foobar" [bug] [in progress] . I don't want to see the whole issue text inside page - it is huge, I want just the link. But after updating to recent master, it is always displaying it (standard theme is used, not bootstrap). Fixed it manually in `style.css`:

``` css
div.issue-doku {
    display: none;
```

It would be great to have an explicit option for this.

**Comment by algorys** [comment]
Ok, update your plugin.

Now try with `short="1"`. That will done the job.

**Comment by selivan** [comment]
That helps :) But it would be nice anyway to have default value for this option. Because most of classic theme users will be unhappy with it, and will need to write `short="1"` every time.

P.S. Thanks a lot for your work.

P.P.S. Plugin update seems to be somehow broken, management page always mentions "new version 2016-09-05 is available", and that doesn't change after update. On latest dokuwiki "Elenor Of Tsort".

**Comment by algorys** [comment]
@selivan you would have possibility to always had short version (permanent in settings ?) or something more short in parameters, like **/s** ?

**Comment by selivan** [comment]
IMHO best way is to define default behavior in settings, because it is used in 99% of cases, and optional explicit parameter `short=0|1` to modify it when you need.

**Comment by algorys** [comment]
Now you can set it in settings and override with parameters.

**Comment by selivan** [comment]
That's cool. Thank you :)
