### ISSUE TITLE
Feature Request: Display all issues of a specific Tracker on a Project?

### ISSUE THREAD

**Issue by therequest** [algorys/redissue#9]
Okay, first of all i love your plugin, but i am missing some options.
i think it would be nice to get all issues from a specific tracker on an project.
i.e. <redissue id=all tracker='errors' project='MYPROJECT' />

maybe options for the for showing the author an the timestamp would also be nice....

But for single issue.linking it is perfect :-)

**Comment by algorys** [comment]
> i think it would be nice to get all issues from a specific tracker on an project.

This is implemented in "dev" branch. Left to make some tests but seems functionnal.

You should know that it may slow down the display of a page if there are many issues to display... 

> maybe options for the for showing the author an the timestamp would also be nice....

Author is normally yet display... for timestamp :+1: I'll look at this.

**Comment by algorys** [comment]
Implemented.

You can also display only a specific tracker for all project, limit response to 10 or more, and others :wink: .

See README or Dokuwiki site for more informations.
